# Generated by Django 3.2.5 on 2022-08-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccesssRecord',
            new_name='AccessRecord',
        ),
    ]
