# Generated by Django 3.2.5 on 2022-08-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_userprofileinfoform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileInfoForm',
            new_name='UserProfileInfo',
        ),
    ]
