name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Conda
      run: |
        sudo apt-get install curl
        cd /tmp
        curl –O https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
        sha256sum Anaconda3–2020.02–Linux–x86_64.sh
        bash Anaconda3-2020.02-Linux-x86_64.sh
        echo '\n'
        echo 'yes'
        echo '\n'
        source ~/.bashrc
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        conda update conda
        conda update anaconda
        conda install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
